batch_export_wdenoise_denoise_only('G:\Project-Swallow\hyx_data', ...
    'G:\Project-Swallow\denoised_hyx_data', ...
    'HeaderLines',1,'Recursive',true, ...
    'Level',4,'Wavelet','sym8', ...
    'Method','Bayes','Rule','Soft','Noise','LevelIndependent', ...
    'DetrendMode','linear');
